name: write_yaml_rules

on:
  push:
    branches:
      - 'master'

jobs:
  write_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - run: pip install PyYAML && pip install -e .
      - run: python .github/workflows/rules_to_yaml.py
      - run: |
          git add rules.yaml
          git diff-index --quiet HEAD || git commit -m "Updating rules.yaml" --author=.